INDIAN_OCCASIONS = [
    "college",
    "office",
    "interview",
    "date",
    "daily casual",
    "travel",
    "wedding guest",
    "haldi",
    "sangeet",
    "mehendi",
    "reception",
    "pooja",
    "festival",
    "family function",
    "business meeting",
    "monsoon day",
    "summer day",
]

MENSWEAR_CATEGORIES = [
    "shirt",
    "t-shirt",
    "polo",
    "kurta",
    "nehru jacket",
    "blazer",
    "jeans",
    "chinos",
    "trousers",
    "dhoti",
    "sherwani",
    "sneakers",
    "loafers",
    "formal shoes",
    "sandals",
    "juttis",
    "watch",
    "belt",
    "grooming",
]

WOMENSWEAR_CATEGORIES = [
    "kurti",
    "kurta",
    "kurta set",
    "dupatta",
    "palazzo",
    "leggings",
    "saree",
    "blouse",
    "lehenga",
    "salwar",
    "churidar",
    "anarkali",
    "ethnic jacket",
    "top",
    "shirt",
    "t-shirt",
    "jeans",
    "skirt",
    "dress",
    "heels",
    "juttis",
    "sandals",
    "sneakers",
    "handbag",
    "jewelry",
]

CLIMATE_TAGS = ["hot_humid", "hot_dry", "monsoon", "winter", "indoor_ac", "outdoor_day", "outdoor_evening"]

STYLE_TAGS = [
    "minimal",
    "smart casual",
    "formal",
    "traditional",
    "ethnic",
    "western",
    "streetwear",
    "elegant",
    "modest",
    "festive",
    "budget-conscious",
]

TAXONOMY = {
    "positioning": "Drape AI: India-first privacy-preserving wardrobe assistant",
    "privacy_contract": "Only structured item/profile features leave the app; photos stay local.",
    "occasions": INDIAN_OCCASIONS,
    "menswear_categories": MENSWEAR_CATEGORIES,
    "womenswear_categories": WOMENSWEAR_CATEGORIES,
    "climate_tags": CLIMATE_TAGS,
    "style_tags": STYLE_TAGS,
}
